const lang = {
  en: {
    search: "Search",
    gptsearch: "GPT Search",
    signIn: "Sign In",
    signUp: "Sign Up",
    signOut: "Sign Out",
    forgotPassword: "Forgot password?",
    rememberMe: "Remember me",
    newToNetflix: "New to Netflix?",
    signUpNow: " Sign up now.",
    signInNow: "Sign in now.",
    captcha:"This page is protected by Google reCAPTCHA to ensure you're not a bot.",
    fullName: "Full Name",
    emailOrMobile: "Email or mobile number",
    password: "Password",
    alreadyRegistered: "Already Registered?",
    unlimitedMoviesTV: "Unlimited movies, TV",
    showsAndMore: "shows and more",
    startsAt: "Starts at ₹149. Cancel at any time.",
    getStarted: "Get Started",
    trendingMovies: "Trending Movies",
    popularMovies: "Popular Movies",
    boxOfficeHitMovies: "Box Office Hit Movies",
    mostWatchedMovies: "Most Watched Movies",
    mostAnticipatedMovies: "Most Anticipated Movies",
    searchTitle: "Let AI be your Movie Guru!",
    searchSubTitle: "Discover Family-Friendly Flicks for a Perfect Movie Night",
    searchPlaceholder: "What would you like to watch today?",
  },
  hi: {
    search: "खोज",
    gptsearch: "GPT खोज",
    signIn: "साइन इन",
    signUp: "साइन अप",
    signOut: "साइन आउट",
    forgotPassword: "पासवर्ड भूल गए?",
    rememberMe: "मुझे याद रखें",
    newToNetflix: "Netflix पर नए हैं?",
    signUpNow: "अभी साइन अप करें।",
    signInNow: "अभी साइन इन करें।",
    captcha:"यह पृष्ठ Google reCAPTCHA द्वारा संरक्षित है ताकि यह सुनिश्चित किया जा सके कि आप बॉट नहीं हैं।",
    fullName: "पूरा नाम",
    emailOrMobile: "ईमेल या मोबाइल नंबर",
    password: "पासवर्ड",
    alreadyRegistered: "पहले से पंजीकृत?",
    unlimitedMoviesTV: "अनलिमिटेड फ़िल्में, टीवी",
    showsAndMore: "शो और बहुत कुछ",
    startsAt: "₹149 से शुरू। कभी भी रद्द करें।",
    getStarted: "शुरू करें",
    trendingMovies: "ट्रेंडिंग फ़िल्में",
    popularMovies: "लोकप्रिय फ़िल्में",
    boxOfficeHitMovies: "बॉक्स ऑफिस हिट फ़िल्में",
    mostWatchedMovies: "सबसे ज्यादा देखी गई फ़िल्में",
    mostAnticipatedMovies: "सबसे अपेक्षित फ़िल्में", 
    searchTitle: "एआई को अपना मूवी गुरु बनने दें!",
    searchSubTitle: "एक परफेक्ट मूवी नाइट के लिए परिवार-हितैषी फ़िल्में खोजें",
    searchPlaceholder: "आज आप क्या देखना चाहेंगे?",
  },
  es: {
    search: "Buscar",
    gptsearch: "Búsqueda GPT",
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    signOut: "Cerrar sesión",
    forgotPassword: "¿Olvidaste tu contraseña?",
    rememberMe: "Recuérdame",
    newToNetflix: "¿Nuevo en Netflix?",
    signUpNow: " Regístrate ahora.",
    signInNow: "Inicia sesión ahora.",
    captcha:"Esta página está protegida por Google reCAPTCHA para garantizar que no eres un bot.",
    fullName: "Nombre completo",
    emailOrMobile: "Correo electrónico o número de móvil",
    password: "Contraseña",
    alreadyRegistered: "¿Ya estás registrado?",
    unlimitedMoviesTV: "Películas y series ilimitadas",
    showsAndMore: "programas y más",
    startsAt: "Desde ₹149. Cancela en cualquier momento.",
    getStarted: "Comenzar",
    trendingMovies: "Películas en tendencia",
    popularMovies: "Películas populares",
    boxOfficeHitMovies: "Éxitos de taquilla",
    mostWatchedMovies: "Películas más vistas",
    mostAnticipatedMovies: "Películas más esperadas",
    searchTitle: "¡Deja que la IA sea tu gurú del cine!",
    searchSubTitle: "Descubre películas familiares para una noche de cine perfecta",
    searchPlaceholder: "¿Qué te gustaría ver hoy?",
  },
  fr: {
    search: "Rechercher",
    gptsearch: "Recherche GPT",
    signIn: "Se connecter",
    signUp: "S’inscrire",
    signOut: "Se déconnecter",
    forgotPassword: "Mot de passe oublié ?",
    rememberMe: "Se souvenir de moi",
    newToNetflix: "Nouveau sur Netflix ?",
    signUpNow: "Inscrivez-vous maintenant.",
    signInNow: "Connectez-vous maintenant.",
    captcha: "Cette page est protégée par Google reCAPTCHA pour garantir que vous n’êtes pas un robot.",
    fullName: "Nom complet",
    emailOrMobile: "E-mail ou numéro de mobile",
    password: "Mot de passe",
    alreadyRegistered: "Déjà inscrit ?",
    unlimitedMoviesTV: "Films et séries illimités",
    showsAndMore: "émissions et plus encore",
    startsAt: "À partir de 149 ₹. Annulez à tout moment.",
    getStarted: "Commencer",
    trendingMovies: "Films tendance",
    popularMovies: "Films populaires",
    boxOfficeHitMovies: "Succès du box-office",
    mostWatchedMovies: "Films les plus regardés",
    mostAnticipatedMovies: "Films les plus attendus",
    searchTitle: "Laissez l’IA être votre guide cinéma !",
    searchSubTitle: "Découvrez des films familiaux pour une soirée parfaite",
    searchPlaceholder: "Que voulez-vous regarder aujourd’hui ?"
  },
  de: {
    search: "Suchen",
    gptsearch: "GPT-Suche",
    signIn: "Anmelden",
    signUp: "Registrieren",
    signOut: "Abmelden",
    forgotPassword: "Passwort vergessen?",
    rememberMe: "Angemeldet bleiben",
    newToNetflix: "Neu bei Netflix?",
    signUpNow: "Jetzt registrieren.",
    signInNow: "Jetzt anmelden.",
    captcha: "Diese Seite ist durch Google reCAPTCHA geschützt, um sicherzustellen, dass Sie kein Bot sind.",
    fullName: "Vollständiger Name",
    emailOrMobile: "E-Mail oder Handynummer",
    password: "Passwort",
    alreadyRegistered: "Bereits registriert?",
    unlimitedMoviesTV: "Unbegrenzte Filme, Serien",
    showsAndMore: "Shows und mehr",
    startsAt: "Beginnt ab ₹149. Jederzeit kündbar.",
    getStarted: "Jetzt starten",
    trendingMovies: "Trendfilme",
    popularMovies: "Beliebte Filme",
    boxOfficeHitMovies: "Kassenschlager",
    mostWatchedMovies: "Meistgesehene Filme",
    mostAnticipatedMovies: "Am meisten erwartete Filme",
    searchTitle: "Lass die KI dein Film-Guru sein!",
    searchSubTitle: "Entdecken Sie familienfreundliche Filme für einen perfekten Filmabend",
    searchPlaceholder: "Was möchten Sie heute anschauen?"
  },
  ja: {
    search: "検索",
    gptsearch: "GPT検索",
    signIn: "サインイン",
    signUp: "サインアップ",
    signOut: "サインアウト",
    forgotPassword: "パスワードをお忘れですか？",
    rememberMe: "ログイン情報を記憶する",
    newToNetflix: "Netflix は初めてですか？",
    signUpNow: "今すぐサインアップ。",
    signInNow: "今すぐサインイン。",
    captcha: "このページは、あなたがボットでないことを確認するために Google reCAPTCHA によって保護されています。",
    fullName: "氏名",
    emailOrMobile: "メールアドレスまたは携帯番号",
    password: "パスワード",
    alreadyRegistered: "すでに登録済みですか？",
    unlimitedMoviesTV: "映画やテレビが見放題",
    showsAndMore: "番組やさらに多く",
    startsAt: "月額149円から。いつでもキャンセル可能。",
    getStarted: "始める",
    trendingMovies: "トレンド映画",
    popularMovies: "人気映画",
    boxOfficeHitMovies: "大ヒット映画",
    mostWatchedMovies: "最も視聴された映画",
    mostAnticipatedMovies: "最も期待される映画",
    searchTitle: "AIをあなたの映画ガイドにしましょう！",
    searchSubTitle: "家族みんなで楽しめる完璧な映画ナイトを見つけよう",
    searchPlaceholder: "今日は何を観たいですか？"
  }


};

export default lang;
